---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:                 # Интерфейс смотрит в Интернет
      addresses:
      - 192.168.255.2/30    # Имеет такой адрес
      routes:
      - to: 0.0.0.0/0       # И ходит куда угодно 
        via: 192.168.255.1  # через 192.168.255.1 (inetRouter)
    enp0s9:                 # Интерфейс cмотрит в сеть Directors
      addresses:
      - 192.168.0.1/28      
    enp0s10:                # Интерфейс cмотрит в сеть Office hardware
      addresses:
      - 192.168.0.33/28     
    enp0s16:                # Интерфейс cмотрит в сеть Wifi
      addresses:
      - 192.168.0.65/26     
    enp0s17:                # Интерфейс cмотрит в сеть 192.168.255.8/29, где есть Office1Router (192.168.255.10/30)
      addresses:
      - 192.168.255.9/30    # Имеет такой адрес
      routes:
      - to: 192.168.2.0/24  # И ходит в сети 192.168.2.0/24
        via: 192.168.255.10 # через 192.168.255.10 (office1Router)
    enp0s18:                # Интерфейс cмотрит в сеть 192.168.255.4/29, где есть Office1Router (192.168.255.4/30)
      addresses:
      - 192.168.255.5/30    # Имеет такой адрес
      routes:
      - to: 192.168.1.0/24  # И ходит в сети 192.168.1.0/24
        via: 192.168.255.6  # через 192.168.255.6 (office2Router)
    enp0s19:                # Интерфейс Vagrant
      addresses:
      - 192.168.56.11/24