---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:                      # Интерфейс смотрит в сеть с inetRouter
      addresses:
      - 192.168.255.6/30        # Имеет такой адрес
      routes:
      - to: 0.0.0.0/0            # И ходит куда угодно 
        via: 192.168.255.5       # через 192.168.255.5  (centralRouter)
    enp0s9:
      addresses:
      - 192.168.1.1/25
    enp0s10:
      addresses:
      - 192.168.1.129/26
    enp0s16:
      addresses:
      - 192.168.1.193/26
    enp0s19:
      addresses:
      - 192.168.56.30/24         # Интерфейс Vagrant
